APP2/urls.py
from django.urls import path
from APP2.views import *
app_name='APP2'

urlpatterns=[
    path('bye/',bye,name='bye'),
]

project9/urls.py
from django.contrib import admin
from django.urls import path,include
from APP1.views import *
import APP2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hai/',hai,name='hai'),
    path('hello/',hello,name='hello'),
    path('APP2/',include('APP2.urls')),
]

APP1/models.py
from django.db import models

# Create your models here.

APP2/models.py
from django.db import models

# Create your models here.

APP1/views.py
from django.shortcuts import render

# Create your views here.
def hai(request):
    return render(request,'hai.html')



def hello(request):
    return render(request,'hello.html')

APP2/views.py
from django.shortcuts import render

# Create your views here.
def bye(request):
    return render(request,'bye.html')

templates/bye.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>THIS IS BYE HTML FILE</h1>
        <h6><a href="{% url 'hai' %}">navigate to hai</a></h6>
        <h6><a href="{% url 'hello' %}">navigate to hello</a></h6>

    </center>
</body>
</html>

templates/hai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>THIS IS HAI HTML PAGE</h1>
        <h6><a href="{% url 'hello' %}">navigate to hello</a></h6>
        <h6><a href="{% url 'APP2:bye' %}"> navigate to bye</a></h6>
    </center>
</body>
</html>

templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>THIS IS HELLO HTML PAGE</h1>
        <h6><a href="{% url 'hai' %}">navigate to hai</a></h6>
        <h6><a href="{% url 'APP2:bye' %}"> navigate to bye</a></h6>
    </center>
</body>
</html>